# Generated by Django 4.0.4 on 2022-05-18 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='country_name',
        ),
        migrations.RemoveField(
            model_name='heuristic',
            name='country_name',
        ),
        migrations.DeleteModel(
            name='country',
        ),
    ]
